import type { BookPassport } from "@/lib/book-passport";
import { computeBookHealth } from "@/lib/book-passport";

/**
 * Preflight logic for the Publishing Control Center's background KDP
 * preparation. Deliberately NOT a second readiness engine: every fact
 * here is read straight off the same BookPassport/computeBookHealth()
 * that /passport and the dashboard already use — this module only adds
 * the one thing genuinely missing from that shared health check, which is
 * per-format completeness (a book can be "healthy" overall while its
 * paperback edition still needs a cover, or while hardcover — which
 * InkFrame can't produce at all yet — was requested anyway).
 *
 * Two tiers, matching the spec's blocker/warning distinction:
 *  - `bookBlockers`: must be fixed before ANY preparation can proceed —
 *    these are the computeBookHealth() checks that apply no matter which
 *    formats were requested (manuscript, metadata, quality gate, rights,
 *    AI disclosure).
 *  - per-format readiness: reported honestly but never blocks the whole
 *    run — a format that isn't ready (or, for hardcover, can never be
 *    ready with InkFrame's current capabilities) is simply left out of
 *    the KDP Ready Package with a clear note, while the formats that ARE
 *    ready still get prepared. This is what lets InkFrame "prepare
 *    everything it legitimately can" instead of refusing outright the
 *    moment one requested format has a gap.
 */

export type FormatType = "ebook" | "paperback" | "hardcover";
export const ALL_FORMATS: FormatType[] = ["ebook", "paperback", "hardcover"];

/**
 * A starting suggestion only — never treated as a real price. Shared
 * between /publish (display) and the background preparation job (the
 * prepared-listing snapshot's fallback), so there's exactly one word-
 * count-based suggestion formula, not two that can drift.
 */
export function suggestPrice(totalWords: number): string {
  if (totalWords < 20000) return "2.99";
  if (totalWords < 50000) return "3.99";
  if (totalWords < 90000) return "4.99";
  return "5.99";
}

export type FormatReadiness = {
  format: FormatType;
  requested: boolean;
  ready: boolean;
  supported: boolean; // false only for hardcover today — a real capability limit, not a fixable gap
  blockers: string[];
  notes: string[];
};

export type BookBlocker = { label: string; route: string };

export type PreflightResult = {
  readinessPct: number;
  bookBlockers: BookBlocker[];
  formats: FormatReadiness[];
  canProceed: boolean; // true once bookBlockers is empty — per-format gaps never block proceeding
};

const BOOK_LEVEL_LABELS = new Set([
  "Manuscript (all chapters approved)",
  "Metadata",
  "Quality gate scored",
  "Rights confirmed",
  "AI-content disclosure acknowledged",
]);

export function runPreflight(
  passport: BookPassport,
  requestedFormats: FormatType[],
  prices: Record<FormatType, string>
): PreflightResult {
  const { checks, readinessPct } = computeBookHealth(passport);

  const bookBlockers: BookBlocker[] = checks
    .filter((c) => BOOK_LEVEL_LABELS.has(c.label) && !c.ok)
    .map((c) => ({ label: c.label, route: c.route }));

  const paperbackEdition = passport.formatting.editions.find((e) => e.formatType === "paperback") ?? null;

  const formats: FormatReadiness[] = ALL_FORMATS.map((format) => {
    const requested = requestedFormats.includes(format);
    const priceSet = prices[format]?.trim() !== "" && !isNaN(Number(prices[format]));

    if (format === "ebook") {
      const blockers: string[] = [];
      if (passport.ebookFormatting.status !== "complete") blockers.push("eBook manuscript (DOCX/EPUB) isn't formatted yet.");
      if (passport.cover.status !== "done") blockers.push("eBook cover isn't finished yet.");
      if (!priceSet) blockers.push("eBook price hasn't been saved yet.");
      return { format, requested, ready: blockers.length === 0, supported: true, blockers, notes: [] };
    }

    if (format === "paperback") {
      const blockers: string[] = [];
      if (paperbackEdition?.status !== "ready") blockers.push("Paperback full-cover PDF isn't generated yet.");
      if (!priceSet) blockers.push("Paperback price hasn't been saved yet.");
      const notes = [
        "Paperback interior PDF isn't generated by InkFrame yet — export the manuscript and lay it out yourself before uploading on KDP.",
      ];
      return { format, requested, ready: blockers.length === 0, supported: true, blockers, notes };
    }

    // hardcover — a real capability limit today, not a gap that can be closed by fixing something.
    return {
      format,
      requested,
      ready: false,
      supported: false,
      blockers: [],
      notes: ["InkFrame doesn't generate hardcover interior or cover files yet — prepare this format directly on KDP."],
    };
  });

  return { readinessPct, bookBlockers, formats, canProceed: bookBlockers.length === 0 };
}
