"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { sharedSecondaryCss } from "@/content/shared-secondary.css";
import { useMyProjects } from "@/lib/useMyProjects";
import ProjectPicker from "@/lib/ProjectPicker";

export const dynamic = "force-dynamic";

type Placement = {
  id: string;
  chapter_id: string | null;
  placement_location: string | null;
  prompt: string | null;
  status: string;
  file_ref: string | null;
};

type ImagesConfig = { image_workflow: string | null; auto_placement_enabled: boolean | null } | null;

export default function ImagesPage() {
  const router = useRouter();
  const supabase = createClient();
  const projects = useMyProjects();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const effectiveId = selectedId ?? (projects && projects.length > 0 ? projects[0].id : null);
  const [config, setConfig] = useState<ImagesConfig>(null);
  const [placements, setPlacements] = useState<Placement[] | null>(null);
  const [chapterNumbers, setChapterNumbers] = useState<Record<string, number>>({});

  useEffect(() => {
    if (!effectiveId) return;
    let cancelled = false;
    (async () => {
      setConfig(null);
      setPlacements(null);
      const [{ data: configData }, { data: placementData }, { data: chapterData }] = await Promise.all([
        supabase.from("project_images").select("image_workflow, auto_placement_enabled").eq("project_id", effectiveId).maybeSingle(),
        supabase
          .from("image_placements")
          .select("id, chapter_id, placement_location, prompt, status, file_ref")
          .eq("project_id", effectiveId),
        supabase.from("chapters").select("id, chapter_number").eq("project_id", effectiveId),
      ]);
      if (cancelled) return;
      setConfig(configData ?? null);
      setPlacements((placementData as Placement[] | undefined) ?? []);
      setChapterNumbers(Object.fromEntries((chapterData ?? []).map((c) => [c.id, c.chapter_number])));
    })();
    return () => {
      cancelled = true;
    };
  }, [effectiveId, supabase]);

  const wantsAutoImages =
    (config?.image_workflow === "Generate Automatically" || config?.image_workflow === "Mixed") &&
    config?.auto_placement_enabled === true;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: sharedSecondaryCss }} />
      <header>
        <div className="logo">
          <span className="ink">Ink</span>
          <span className="frame">Frame</span>
        </div>
        <button className="back-btn" onClick={() => router.push("/dashboard")}>
          ← Back to Dashboard
        </button>
      </header>
      <div className="wrap">
        <h1>🖼 Images</h1>
        <p className="subtitle">
          Interior illustrations InkFrame decided this book&apos;s chapters would benefit from, with real
          artwork generated by OpenAI or Gemini where a placement has finished rendering. Uploading your own
          images isn&apos;t built yet — see Cover Designer for the same real-generation approach applied to
          cover art.
        </p>

        <ProjectPicker projects={projects} selectedId={effectiveId} onSelect={setSelectedId} />

        {effectiveId && (
          <div className="panel">
            {(config === null || placements === null) && <p className="hint">Loading…</p>}

            {config && config.image_workflow === "No Images" && (
              <p className="hint">This book was set up with no interior images — nothing to show here.</p>
            )}

            {config && config.image_workflow === "User Upload" && (
              <p className="hint">
                This book was set up for you to upload your own images — InkFrame doesn&apos;t generate or place
                them automatically. Manual upload isn&apos;t built yet.
              </p>
            )}

            {config && !wantsAutoImages && config.image_workflow !== "No Images" && config.image_workflow !== "User Upload" && (
              <p className="hint">
                This book didn&apos;t ask InkFrame to recommend image placements automatically (Step 7 of the
                wizard) — nothing to show here.
              </p>
            )}

            {config && wantsAutoImages && placements && placements.length === 0 && (
              <p className="hint">
                No interior images yet for this book — placements are decided automatically once all chapters
                are quality-approved and cover art is done.
              </p>
            )}

            {config &&
              wantsAutoImages &&
              placements?.map((p) => (
                <div key={p.id} style={{ marginBottom: "20px", fontSize: "13px" }}>
                  <div style={{ fontWeight: 600, marginBottom: "4px" }}>
                    Chapter {p.chapter_id ? (chapterNumbers[p.chapter_id] ?? "?") : "?"}
                    {p.placement_location ? ` — ${p.placement_location}` : ""}
                  </div>
                  {p.file_ref && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={p.file_ref}
                      alt={`Interior illustration for chapter ${p.chapter_id ? chapterNumbers[p.chapter_id] : ""}`}
                      style={{ maxWidth: "260px", width: "100%", borderRadius: "8px", display: "block", marginBottom: "8px" }}
                    />
                  )}
                  <div style={{ color: "var(--muted)" }}>{p.prompt}</div>
                </div>
              ))}
          </div>
        )}
      </div>
    </>
  );
}
